version: '3'
services:
  app:
    build: ./src/smp_scenario
    volumes:
      - ./:/app
    ports:
     - "5021:5021"
#  app_dash:
#    build: ./src/smp_dash
#    volumes:
#      - ./:/app
#    ports:
#      - "5020:5020"