version: '3'
services:
#  model:
#    build: ./src/smp_scenario
#    volumes:
#      - ./:/app
#    ports:
#     - "5001:5001"
  dash2:
    build: ./src/smp_dash
    volumes:
      - ./:/app
    ports:
      - "5020:5020"